#!/bin/bash

# Bash function to display information about subdomains
display_subdomain_info() {
  local domain=$1
  local subdomain=$2

  if [ -z "$subdomain" ]; then
    # Display information for all subdomains
    for sub in "www" "lb-01" "web-01" "web-02"; do
      record_type=$(dig +short "$subdomain.$domain" | awk '{print $4}')
      destination=$(dig +short "$subdomain.$domain")
      echo "The subdomain $sub is a $record_type record and points to $destination"
    done
  else
    # Display information for specific subdomain
    record_type=$(dig +short "$subdomain.$domain" | awk '{print $4}')
    destination=$(dig +short "$subdomain.$domain")
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
  fi
}

# Main script
domain=$1
subdomain=$2

# Ignore shellcheck case SC2086
display_subdomain_info "$domain" "$subdomain"
